// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC36z5ITugERMG51nIzyQ09n_01da0AzvU',
    appId: '1:750455912353:web:7fdb00455fdb4011cdfde0',
    messagingSenderId: '750455912353',
    projectId: 'anchor-app-48ad7',
    authDomain: 'anchor-app-48ad7.firebaseapp.com',
    storageBucket: 'anchor-app-48ad7.firebasestorage.app',
    measurementId: 'G-XZ4Q2DXZYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwjU39VQIFAcR9ZhddzvcTzRn9n6r--4c',
    appId: '1:750455912353:android:674840eed872740ccdfde0',
    messagingSenderId: '750455912353',
    projectId: 'anchor-app-48ad7',
    storageBucket: 'anchor-app-48ad7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7nXQz4qgxfUr2pizIfUEEZUX3YDFKM40',
    appId: '1:750455912353:ios:760b18c106036363cdfde0',
    messagingSenderId: '750455912353',
    projectId: 'anchor-app-48ad7',
    storageBucket: 'anchor-app-48ad7.firebasestorage.app',
    iosBundleId: 'com.example.anchorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7nXQz4qgxfUr2pizIfUEEZUX3YDFKM40',
    appId: '1:750455912353:ios:760b18c106036363cdfde0',
    messagingSenderId: '750455912353',
    projectId: 'anchor-app-48ad7',
    storageBucket: 'anchor-app-48ad7.firebasestorage.app',
    iosBundleId: 'com.example.anchorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC36z5ITugERMG51nIzyQ09n_01da0AzvU',
    appId: '1:750455912353:web:a227437b4086d83bcdfde0',
    messagingSenderId: '750455912353',
    projectId: 'anchor-app-48ad7',
    authDomain: 'anchor-app-48ad7.firebaseapp.com',
    storageBucket: 'anchor-app-48ad7.firebasestorage.app',
    measurementId: 'G-B04F45MJN8',
  );
}
